version: 0.2

phases:
  pre_build:
    commands:

      - echo Logging in to DockerHub
      - aws --version
      - docker login -u bassam123 -p docker123@@
      - REPOSITORY_URI=bassam123/csvfiltering:tagname
  build:
    commands:
      - mvn clean install
      - echo Building Docker image
      - docker build -t bassam123/csvfiltering:tagname .
      - docker push docker.io/bassam123/csvfiltering:tagname
      - docker push docker.io/bassam123/csvfiltering --all-tags

  post_build:
    commands:
      - echo Build completed on `date`
