version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub

  build:
    commands:
      - mvn test
      - mvn clean install
      - echo Building Docker image

  post_build:
    commands:
      - mvn verify
      - echo Build completed on `date`